// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bow2.FA.Models
{
    public partial class Endpoint
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public short State { get; set; }
        public DateTime? Lastmodified { get; set; }
        public string Data { get; set; }
    }
}