// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bow2.FA.Models
{
    public partial class League
    {
        public League()
        {
            Match = new HashSet<Match>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public short? YearFrom { get; set; }
        public short? YearTo { get; set; }
        public string Country { get; set; }
        public short Sport { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}