// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bow2.FA.Models
{
    public partial class Match
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int IdTeam1 { get; set; }
        public int IdTeam2 { get; set; }
        public int IdLeague { get; set; }
        public string EventRound { get; set; }
        public string EventHeader { get; set; }
        public DateTime Datestamp { get; set; }
        public short? Pts1Fulltime { get; set; }
        public short? Pts2Fulltime { get; set; }
        public short? Pts11 { get; set; }
        public short? Pts12 { get; set; }
        public short? Pts13 { get; set; }
        public short? Pts21 { get; set; }
        public short? Pts22 { get; set; }
        public short? Pts23 { get; set; }

        public virtual League IdLeagueNavigation { get; set; }
        public virtual Team IdTeam1Navigation { get; set; }
        public virtual Team IdTeam2Navigation { get; set; }
    }
}