// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bow2.FA.Models
{
    public partial class Match
    {
        public int Id { get; set; }
        public int IdTeam1 { get; set; }
        public int IdTeam2 { get; set; }
        public int IdLeague { get; set; }
        public string EventRound { get; set; }
        public string EventTitle { get; set; }
        public DateTime Datestamp { get; set; }
        public short? Pts1 { get; set; }
        public short? Pts2 { get; set; }

        public virtual League IdLeagueNavigation { get; set; }
        public virtual Team IdTeam1Navigation { get; set; }
        public virtual Team IdTeam2Navigation { get; set; }
    }
}