// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bow2.FA.Models
{
    public partial class Team
    {
        public Team()
        {
            MatchIdTeam1Navigation = new HashSet<Match>();
            MatchIdTeam2Navigation = new HashSet<Match>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Match> MatchIdTeam1Navigation { get; set; }
        public virtual ICollection<Match> MatchIdTeam2Navigation { get; set; }
    }
}